### ISSUE TITLE
Some `<d-math>` tags overflow on mobile

### ISSUE THREAD

**Issue by ludwigschubert** [distillpub/post--bayesian-optimization#15]
Hi Apoorv and Nipun! Congrats on the publication! ^_^
Before putting it on production, I fixed some things I perceived as styling issues. (Take a look at commits between b3de9795362cf44046c755a546f7db402722122d and f25b8373d10750563aca4604816b79dcc56e439b — let me know if you disagree with any of the changes; none of this is dogmatic.)

One issue I only fixed quickly but that may benefit from your attention is that some of the formulas don't break into multiple lines, and so are too large on mobile. I worked around that in cc60b27896a6ab414e994b4414ea511603a9318a by making those scrollable, but that's not ideal as someone may miss that they can scroll a formula. If you have the time, I'd appreciate if you wen through your article on a smartphone screen and considered breaking wide formulas into multiple lines.

Again, congrats on your publication!
—Ludwig, for the Distill editorial team.

**Comment by ludwigschubert** [comment]
![image](https://user-images.githubusercontent.com/1167977/81135570-97105c00-8f0d-11ea-96c1-e0042d1913f4.png)
Here's an example of an overflowing formula.

**Comment by apoorvagnihotri** [comment]
@ludwigschubert Thanks for helping with this! We will update them accordingly. :)

**Comment by apoorvagnihotri** [comment]
Hi @ludwigschubert. I am not able to see the changes in the article, how long does it take to get updated?
