### ISSUE TITLE
Website needs to be updated to new index.html

### ISSUE THREAD

**Issue by jvanheugten** [distillpub/post--bayesian-optimization#17]
The brackets in this formula are correct: https://github.com/distillpub/post--bayesian-optimization/blob/822b3fa57a286d94cf1b65878488f06e56f2114d/public/index.html#L401
But when displayed on the website, they are wrong: https://distill.pub/2020/bayesian-optimization/
![image](https://user-images.githubusercontent.com/12444498/82141242-cd66a900-9834-11ea-9ca6-cdfbc87c64f6.png)

**Comment by jvanheugten** [comment]
Would also be good to run this article through a word processor with spelling/grammar checking as some of the English is a bit broken, for example: 
https://github.com/distillpub/post--bayesian-optimization/blob/822b3fa57a286d94cf1b65878488f06e56f2114d/public/index.html#L590
https://github.com/distillpub/post--bayesian-optimization/blob/822b3fa57a286d94cf1b65878488f06e56f2114d/public/index.html#L575
Style of writing is very conversational, but might be intended.

**Comment by apoorvagnihotri** [comment]
Hi @colah, I updated the article 2 days [822b3fa57a286d94cf1b65878488f06e56f2114d] ago but the article has not updated on distill.pub yet. Can you please help me out with any steps that I might have missed?

**Comment by apoorvagnihotri** [comment]
Hi @jvanheugten,
Thanks a lot for creating an issue here with such rigor. We appreciate your help. :)

> But when displayed on the website, they are wrong: https://distill.pub/2020/bayesian-optimization/

I think master is a protected branch, and therefore, there might be more steps before I can update the rendered article. 

> Would also be good to run this article through a word processor with spelling/grammar checking as some of the English is a bit broken, for example:

- We have addressed the issues in this commit. [16e76f2833ec1fc9600d03c4ca7b1126b9ebe7f2]
- Sure, we will run the article through a word processor and correct any issue it as able to find.

**Comment by apoorvagnihotri** [comment]
Closing this issue, as the article has been updated.
