### ISSUE TITLE
Probability of Improvement

### ISSUE THREAD

**Issue by itsaark** [distillpub/post--bayesian-optimization#19]
I don't think the parentheses for the last step makes sense to me
<img width="529" alt="Screen Shot 2020-05-23 at 4 14 17 PM" src="https://user-images.githubusercontent.com/2403867/82742250-913db780-9d10-11ea-8880-8118c837ba46.png">
 
Shouldn't it be like this?
<img width="718" alt="Screen Shot 2020-05-23 at 4 21 29 PM" src="https://user-images.githubusercontent.com/2403867/82742325-7fa8df80-9d11-11ea-9a80-674b0613715f.png">

**Comment by apoorvagnihotri** [comment]
Thank you for your issue, we are updating the post. Please find this issue already raised here #17.

**Comment by apoorvagnihotri** [comment]
Closing this issue, as the article has been updated.
